theme: jekyll-theme-minimal
title: Paul Z. Chen
logo: [headshot](https://media-exp1.licdn.com/dms/image/C4E03AQHo2PCKrcAiUQ/profile-displayphoto-shrink_400_400/0/1521860909911?e=1627516800&v=beta&t=UpsTF62w5eM0fDP7gAGv2qHMTFqhWzBGPt7NaL5dHy8)
show_downloads: ["true"]
description: PhD student, University of Toronto
description: page updated June 2021
github:
  is_project_page: false
