theme: jekyll-theme-minimal
title: Paul Z. Chen
logo: [href="https://media-exp1.licdn.com/dms/image/C4E03AQHo2PCKrcAiUQ/profile-displayphoto-shrink_800_800/0/1521860909911?e=1628121600&v=beta&t=7lP_9DrU8E9IELI6mE2NXNf8YEf2XMg2RetQS8KhFus"]
show_downloads: ["false"]
description: PhD student, University of Toronto
github:
  is_project_page: false
